### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by barneyhill** [benjeffery/ukb#15]
Running `python3.9 snakemake-with-dask.py --cores 1` with 
```
vcf_to_zarr:
  # These parameters influence the peak RAM usage of the vcf_to_zarr steps
  # For a ~100,000 samples VCF these settings result in about 16GB peak RAM usage
  # per core. If you have less RAM or more samples you may need to reduce the
  # values here, keeping chunk_length > temp_chunk_length > read_chunk_length.
  read_chunk_length: 1000
  temp_chunk_length: 5000
  chunk_length: 10000
  chunk_width: 1500
  # Temp files are deleted serially, so with large VCFs on slow NFS mounts this
  # can take a long time. If you have a fast filesystem you can set this to False
  retain_temp_files: True
```

I get the following errors. Any idea what could be the issue here?
[output.log](https://github.com/benjeffery/ukb/files/12781019/output.log)

Many Thanks,
Barney
